[project]
name = "throttler"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "freezegun>=1.5.5",
    "pytest>=8.4.2",
]
